# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import delegator_pb2 as delegator__pb2


class DelegatorServiceStub(object):
    """*
    The main service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.spawnServer = channel.unary_unary(
                '/DelegatorService/spawnServer',
                request_serializer=delegator__pb2.Port.SerializeToString,
                response_deserializer=delegator__pb2.Port.FromString,
                )


class DelegatorServiceServicer(object):
    """*
    The main service.
    """

    def spawnServer(self, request, context):
        """* Spawns a server *
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DelegatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'spawnServer': grpc.unary_unary_rpc_method_handler(
                    servicer.spawnServer,
                    request_deserializer=delegator__pb2.Port.FromString,
                    response_serializer=delegator__pb2.Port.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DelegatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DelegatorService(object):
    """*
    The main service.
    """

    @staticmethod
    def spawnServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DelegatorService/spawnServer',
            delegator__pb2.Port.SerializeToString,
            delegator__pb2.Port.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
