# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import delegator_pb2 as delegator__pb2


class DelegatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpawnNewServer = channel.unary_unary(
                '/Delegator/SpawnNewServer',
                request_serializer=delegator__pb2.ServerConfig.SerializeToString,
                response_deserializer=delegator__pb2.Ports.FromString,
                )
        self.CloseServer = channel.unary_unary(
                '/Delegator/CloseServer',
                request_serializer=delegator__pb2.Port.SerializeToString,
                response_deserializer=delegator__pb2.Empty.FromString,
                )


class DelegatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SpawnNewServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DelegatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpawnNewServer': grpc.unary_unary_rpc_method_handler(
                    servicer.SpawnNewServer,
                    request_deserializer=delegator__pb2.ServerConfig.FromString,
                    response_serializer=delegator__pb2.Ports.SerializeToString,
            ),
            'CloseServer': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseServer,
                    request_deserializer=delegator__pb2.Port.FromString,
                    response_serializer=delegator__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Delegator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Delegator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SpawnNewServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Delegator/SpawnNewServer',
            delegator__pb2.ServerConfig.SerializeToString,
            delegator__pb2.Ports.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CloseServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Delegator/CloseServer',
            delegator__pb2.Port.SerializeToString,
            delegator__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
