# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_pb2 as test__pb2


class DelegatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetColorOf = channel.unary_unary(
                '/Delegator/GetColorOf',
                request_serializer=test__pb2.Block.SerializeToString,
                response_deserializer=test__pb2.Color.FromString,
                )


class DelegatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetColorOf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DelegatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetColorOf': grpc.unary_unary_rpc_method_handler(
                    servicer.GetColorOf,
                    request_deserializer=test__pb2.Block.FromString,
                    response_serializer=test__pb2.Color.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Delegator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Delegator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetColorOf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Delegator/GetColorOf',
            test__pb2.Block.SerializeToString,
            test__pb2.Color.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
